server:
    error:
        include-stacktrace: always

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/alurabackendchallenge?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
    jackson:
        date-format: dd-MM-yyyy
