server:




#
#server:
#    error:
#        include-stacktrace: always
#
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/alurabackendchallenge?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExists=true
#        username: root
#        password: root
#    jpa:
#        hibernate:
#            ddl-auto: update
